site_name: Spiel

repo_url: https://github.com/JoshKarpel/spiel

extra_css:
  - assets/style.css

theme:
  name: material
  favicon: assets/favicon.png
  icon:
    logo: fontawesome/solid/person-chalkboard
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      media: "(prefers-color-scheme: light)"
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      media: "(prefers-color-scheme: dark)"
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - content.code.annotate

plugins:
  - tags
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            heading_level: 3
            docstring_section_style: spacy
            merge_init_into_class: true
            show_if_no_docstring: true
            show_source: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JoshKarpel/spiel
      name: Spiel on GitHub

nav:
  - Introduction: index.md
  - Sandboxed Execution: sandboxed-execution.md
  - Presenting: presenting.md
