name: test-docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2.4.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0
      with:
        install: true
    - name: Build Image
      uses: docker/build-push-action@v2.7.0
      with:
        file: ./docker/Dockerfile
        pull: true
        push: false
